#!/usr/bin/ruby
#
# Uninstall MacPorts packages that have newer versions installed

require 'optparse'

simulate = false
OptionParser.new do |opts|
	opts.on("-n", "--simulate", "Just print the packages to remove") do
		simulate = true
	end
end.parse!

pkgs = {}
IO.popen('port echo installed') do |f|
	f.each do |line|
		md = /^(\S+)\s+([^\s+]+)(\+\S+)?/.match(line) or next
    name, vers, var = *md.captures
		pkg = name + (var || '')
    fullname = name + vers + (var || '')
		(pkgs[pkg] ||= []) << { :vers => vers, :fullname => fullname }
	end
end
pkgs.reject! { |p,vs| vs.size == 1 }
# Latest version is the last one
pkgs.each { |pkg, vs| vs.pop }

if simulate
	pkgs.keys.sort.each do |p|
		puts "%s: %s" % [p, pkgs[p].map { |v| v[:vers] }.join(', ')]
	end
else
	remove = []
	pkgs.each { |pkg, vs| remove.concat(vs.map { |v| v[:fullname] }) }

  exec('sudo', 'port', 'uninstall', *remove) unless remove.empty?
end
